### ISSUE TITLE
Request multiple login example

### ISSUE THREAD

**Issue by ronjunevaldoz** [seishun/node-steam#103]
I need an idea on how to multiple log in in proper way.

**Comment by maximski** [comment]
I am interested in this issue, too. I didn't try anything yet, but I am going to. My approach will probably be to just call my script multiple times for each bot account with different login params, but I feel like the sentry will cause issues, because hash is stored only for one account at the same time in the sentry, isn't it? So if I login with the second bot account, the first one will lose its sentry.

**Comment by scholtzm** [comment]
Well, that depends on your sentry handling. You can use 2 separate files... :smile:
