### ISSUE TITLE
"Sentry" event not firing

### ISSUE THREAD

**Issue by Lamb3rt** [seishun/node-steam#178]
As in topic. First of all, it worked up to some point and after 50-60 successful logins (I had to provide Steam Guard code each time, since I was yet grasping concept of this hash thing, but event was properly firing) it suddenly stopped firing. However it does work properly for another (years-old) account whole time, but not for my new, test one. This is important, because it shows that problem doesn't lie in my code.

I also can't register my own hash - it's ignored even if I properly call logOn method with both valid Steam Guard code and my own hash and then try to provide only hash, without code. I'm simply getting logon error 63 then. 

So my first guess is that it's not a problem in node-steam, but rather something on Valve's end - but still possibility of such error could be mentioned around "logOn" method description.

**Comment by Lamb3rt** [comment]
I checked it now and it works properly. I had to trigger some limit on Valve's side.

**Comment by graycatfromspace** [comment]
please elaborate?

**Comment by seishun** [comment]
You're right, it's a Steam weirdness, and these kinds of inexplicable surprises from Valve are the reason node-steam has gradually moved from trying to encapsulate the Steam protocol (like the Steam client does) to being a simple wrapper.

I've moved most of the logOn description to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs) that anyone can edit instead of (rightfully) submitting issues when such surprises occur.

Regarding your issue, I can have a guess what happened. Whenever node-steam received a sentry, it automatically accepted it by sending a response, even though you didn't handle 'sentry'. If Steam saves all of them, it's reasonable to expect that there is a certain limit on their count. This is another reason why node-steam doesn't auto-accept sentries anymore. (see ['updateMachineAuth'](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#updatemachineauth))

**Comment by Noiwex** [comment]
ehh, how do I use updateMachineAuth, documentation is too confusing and there is no examples

**Comment by scholtzm** [comment]
```js
steamUser.on('updateMachineAuth', function(sentry, callback) {
  fs.writeFileSync('filename', sentry.bytes);
  callback({ sha_file: calc_sha1(sentry.bytes) });
});
```

`calc_sha1` is a function which calculates SHA-1 checksum

**Comment by Noiwex** [comment]
Ah, this is steamuser event, much appreciated.
