### ISSUE TITLE
Getting error 63

### ISSUE THREAD

**Issue by MajorErection** [seishun/node-steam#205]
I'm getting error 63 plus the auth code in my email.
This is my code so far,

    var steamClient = new Steam.SteamClient();
    var steamTrade = new SteamTrade();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);

   steamClient.connect();

    console.log("Steam Client Connected")

    steamUser.on('updateMachineAuth', function(sentry, callback) {
      fs.writeFileSync('sentryfile', sentry.bytes );

        callback({ sha_file: getSHA1(sentry.bytes) });
    });

    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read(); };
        
     console.log("Steam User Connecting")

     steamClient.on('connected', function () {
         steamUser.logOn({
             account_name: config.steam.accountName,
             password: config.steam.password,
             sha_sentryfile: fs.readFileSync('sentryfile'),
           })
        });

         steamClient.on('logOnResponse', function (logonResp) {
             console.log('Error ' + logonResp.eresult);
             if (logonResp.eresult == Steam.EResult.OK) {
                 console.log("Steam User Connected")
                 steamFriends.setPersonaState(Steam.EPersonaState.Online);
             }
         });

**Comment by seishun** [comment]
That's the expected behavior. The value of `eresult`, as well as the rest of the `CMsgClientLogonResponse` object, comes directly from Steam and is outside the scope of responsibility of node-steam. The meaning of various EResult values should be discussed elsewhere (e.g. [SteamRE group](http://steamcommunity.com/groups/SteamRE) or #opensteamworks on irc.gamesurge.net). However, a list of possible values for the `eresult` field would be a useful addition to the [wiki](https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogonresponse) - you're welcome to contribute.
