### ISSUE TITLE
Pause while logged in from a another location then reconnect?

### ISSUE THREAD

**Issue by Juksern** [seishun/node-steam#230]
Hey!

I'm having a little issue, which I'm not sure how I should fix,
So I have made a script where I have multiple games running, this script is running on my second computer.
But when I'm logging in on my main computer to play the games again, the script crashes and I have to manually restart it.

Is there a way where I can "pause" the script from running while I'm logged on my main computer, then restart again when I'm logging off from the steam account?

It would be kinda silly if I had this running on something like a VPS and I have to login into the VPS everytime to restart the script after playing :)

**Comment by seishun** [comment]
Even if you suspended the execution of the script while logging on elsewhere, you would find that you've been logged off and disconnected once you wake it up. And how exactly are you planning to inform the script that it's time to wake up without logging into the VPS?

And the library doesn't crash. Your script crashes because it's not handling logoffs properly.

Anyway, closing since it's not a library issue.

**Comment by Efreak** [comment]
Require express. Have your script start its functions when you visit a page. This way you can just open that page in your browser when you're done playing, without logging into your vps.

Alternatively, set a reconnect timer when node-steam gets disconnected/logged off.
