### ISSUE TITLE
Socket timed out

### ISSUE THREAD

**Issue by Marnas9** [seishun/node-steam#276]
I haven't changed anything and it just throws this every few minutes:
socket timed out
What could cause it? Sometimes it just crashes, with no error at all. All of this started today.

**Comment by seishun** [comment]
It outputs this line because that's what your handler for the 'debug' event does. Did you write your bot yourself?

As for why this line is passed to the 'debug' event, that's because node-steam is trying to reconnect, failing and retrying. It's failing because you either have connection issues, or Steam servers are currently down.
