### ISSUE TITLE
Feature Request: ChangeSets functionality

### ISSUE THREAD

**Issue by undeclared** [seishun/node-steam#40]
Hi,

I would be extremely grateful if you could add a way to receive changesets..

I was attempting to do this via toGC/fromGC but as you told me, that's not what we are supposed to use..

To be more specific, looking for PICSChangesSinceRequest/PICSChangesSinceResponse I believe (I think the response is the callback)

Thanks

**Comment by DoctorMcKay** [comment]
This will never happen in node-steam, I guess you check out DoctorMcKay/node-steam-user.

**Comment by seishun** [comment]
node-steam is modular since version 1.0.0, and I believe that it should only contain the essential functionality out-of-box, with more specialized functionality provided by third-party modules.

I think a handler for PICS functionality would make a great module. See ['message'/send](https://github.com/seishun/node-steam#messagesend) and [node-steam-resources](https://github.com/seishun/node-steam-resources) if you would like to work on it. Feel free to post any questions here - perhaps I'll add a page to the wiki about writing third-party handlers if there is interest.
