### ISSUE TITLE
Request: Group names in steam.groups

### ISSUE THREAD

**Issue by Efreak** [seishun/node-steam#85]
steamClient.users{} has playerName and etc. Is it possible to add the steam group name to steamClient.chatRooms{} as well, or does that need to be done separately? It might be useful to have them added to the groups object as well, since a bot is not necessarily in all the groupchats all the time.

Also, [gamesPlayed](https://github.com/seishun/node-steam#gamesplayedappids) still works for multiple games. [At least, it does for me](http://steamcommunity.com/id/mileyverisse).

**Comment by mcd1992** [comment]
I agree with this addition, currently the only way to get the group name is through the group chat invite event. This makes it difficult to have a bot auto-join a group chat and know where it is since you just join with the groupid.

**Comment by seishun** [comment]
Do you have an idea for the API to emit and possibly store group names? Group data is received in [this protobuf](https://github.com/SteamRE/SteamKit/blob/a7368f237b594ee5bf9797a35f49f1c5034102e8/Resources/Protobufs/steamclient/steammessages_clientserver.proto#L1341-L1369). I don't like @DoctorMcKay's solution because it ignores `user_counts`. The simplest would be to pass the whole `CMsgClientClanState` object to the user.

Also I'm currently working on a [modular API](https://github.com/seishun/node-steam/commits/1.0.0-strawman) for node-steam. It's going to break things anyway, so feel free to suggest better names for the events/properties that don't involve the confusing "group"/"groupData" pair.

**Comment by seishun** [comment]
Added in master as [`clanStates`](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#clanstates) and ['clanState'](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#clanstate).
