### ISSUE TITLE
Reconnecting accounts still include authCode in logOn request.

### ISSUE THREAD

**Issue by Shadiku** [seishun/node-steam#98]
When signing into a Steam Guard protected account without a sentry file or authCode.

    debug: connected
    debug: encrypt request
    debug: handshake complete
    debug: logon fail: 63, sessionID: 8359443
    error: Error: Logon fail: 63

Logging in again after providing the authCode in logOnDetails.

    debug: connected
    debug: encrypt request
    debug: handshake complete

Some time later the connection to Steam is lost. authCode is still present in the logOnDetails so the account will never reconnect. (#77)

    debug: socket ended
    debug: socket closed
    debug: connecting to 81.171.115.34:27019
    debug: connected
    debug: encrypt request
    debug: handshake complete
    debug: logon fail: 65, sessionID: 5654491
    error: Error: Logon fail: 65

I suspect dropping authCode and adding shaSentryfile to .logOnDetails once connected would work but I wonder if there's a better way.

**Comment by seishun** [comment]
>Could authCode be deleted in the sentry event? 

This won't work if the user logs on with both authCode and shaSentryFile, as there would be no sentry event.

It could delete authCode immediately if shaSentryFile is present and otherwise wait for sentry, but I don't like such inconsistency.

I will try to trigger a disconnection with an actual Steam client and see what it does when I have time. (Or maybe someone else can do it)

**Comment by seishun** [comment]
node-steam master no longer auto-reconnects, so this no longer applies.
